name: "Deploy to Server (Beta)"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
    
    - name: "Build deployment code"
      run: |
        npm install
        CI=false npm run build
    
    - name: "Configure SSH"
      env:
        remote_key: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$remote_key" > ~/.ssh/id_github
        chmod 600 ~/.ssh/id_github
    
    - name: "Deploy with rsync"
      env:
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        local_dir: "dist/"
        remote_dir: ${{ secrets.DEPLOY_DIR }}
      run: rsync -arvz -e "ssh -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}/multicalc-beta
    
    - name: "Clean up SSH"
      run: rm ~/.ssh/id_github
        
        
