name: "Deploy to Server (Beta)"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
    
    - run: npm install
    - run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-arvz -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_DIR }}/multicalc-beta
          EXCLUDE: "/dist/, /node_modules/"

    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.DEPLOY_KEY }}
    #     known_hosts: unnecessary

    # - name: Add Known Hosts
    #   run: |
    #     # REMOTE_HOST=`nslookup rxcalc.net | grep -E -o -m 2 'Address\:.*' | tail -1 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
    #     # echo $REMOTE_HOST
    #     ssh-keyscan -t rsa -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    # - name: Deploy with rsync
    #   run: rsync -arvz -e "ssh -o HostKeyAlgorithms=+ssh-rsa" ./dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_DIR }}/multicalc-beta
